server:
  port: 8181

spring:
  application:
    name: RowBank

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rowbank
    username: root
    password: 10850106Row
    initialization-mode: always
#    schema: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG

app:
  jwtSecret: 6B58703273357638792F423F4428472B4B6250655368566D597133743677397A244326462948404D635166546A576E5A7234753778214125442A472D4B614E64
  jwtExpirationInMs: 604800000
  cors:
    allowedOrigins: http://localhost:3000

banking:
  flexible:
    interestRate: 0.07
  fixed:
    interestRate: 0.09

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    description: This is a banking web application (Row Bank)
    version: 1.0.0

---
spring:
  config:
    import: optional:secrets_prod.yaml
    activate:
      on-profile: prod


server:
  port: 8282



info:
  app:
    description: This is a banking web application (Row Bank)
    version: 1.0.0

---
server:
  port: 8080
spring:
  config:
    import: optional:secrets_dev.yaml
    activate:
      on-profile: dev
  application:
    name: RowBank

info:
  app:
    description: This is a banking web application (Row Bank)
    version: 1.0.0


