server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rowbank
    username: root
    password: 10850106Row
    initialization-mode: always
    schema: classpath:schema.sql

    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 282967731613-5qerko0r19hic6apbduam0vetocsgucm.apps.googleusercontent.com
              client-secret: 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
            #            scope:
            #              - email
            #              - profile
            github:
              client-id: Iv23liuCJYG4fWjfw6Cb
              client-secret: c192985f0804156cfadc4bb2c5caca89bd79c6a4
    #            scope:
    #              - email
    #              - profile

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


#jwt:
#  header: AuthHeader
#  key: e038394bc945eed83ca8797aae26fddfae91b175fc4dd26339dd6cb8066c65b892d6ac07c0a3c0384601896ade90551905460af66e4864e9c71a31d6d523c136
#  expiration: 36000

banking:
  flexible:
    interestRate: 0.07
  fixed:
    interestRate: 0.09

logging:
  level:
    org.hibernate.SQL: DEBUG

app:
  jwtSecret: 6B58703273357638792F423F4428472B4B6250655368566D597133743677397A244326462948404D635166546A576E5A7234753778214125442A472D4B614E64
  jwtExpirationInMs: 604800000
  cors:
    allowedOrigins: http://localhost:3000
  google:
    client-id: Iv23liuCJYG4fWjfw6Cb
    client-secret: c192985f0804156cfadc4bb2c5caca89bd79c6a4